---
- name: Install common apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ elk_common_packages }}"

# - name: Monit conf file
#   copy:
#     src: monitrc
#     dest: /etc/monit/monitrc
#     owner: root
#     group: root
#     mode: 600
#   notify: restart monit

- name: Install Java
  include: java.yml

- name: Elastic apt GPG key
  apt_key:
      url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Logstash
  include: logstash.yml

- name: Install Nginx
  include: nginx.yml

- name: Install Kibana
  include: kibana.yml
